spring:
  application:
    name: COLLABIDE


  profiles:
    active: dev

logging:
  level:
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG

app:
  auth:
    base-url: ${AUTH_SERVICE_URL:http://localhost:8080}

server:
  port: ${PORT:8081}
  address: 0.0.0.0